version: '3.4'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=guitarist097865
      - MARIADB_USER=inferback
      - MARIADB_PASSWORD=inferback
      - MARIADB_DATABASE=inferback
    volumes:
      - .:/var/lib/mysql/data
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
