apiVersion: v1
kind: Service
metadata:
    - name: db
      labels:
            name: mariadb_service
            app: inferback
spec:
    type: NodePort
    ports:
        - port: 3306
          targetPort: 3306
          nodePort: 3306
    selector:
        name: mariadb_pod
        app: inferback
